In [2]:
import numpy as np
import numpy.linalg as la
from matplotlib import pyplot as plt
plt.rcParams.update({'font.size': 15})
#%config InlineBackend.figure_format='retina'

In [23]:
A = np.array([
    [1, 0, -1],
    [-2, 3, 0],
    [1, -3, 2]
])
I = np.eye(A.shape[0])

invA = la.solve(A, I)

invA - la.inv(A)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
A = np.array([
    [1, -1, 4],
    [2, -3, 8],
    [1, -2, 4]
])
I = np.eye(A.shape[0])
# this will fail
#la.solve(A, I)


In [4]:
N = 1000
A = np.random.rand(N, N)
b = np.random.rand(N, 1)

In [6]:
A

array([[0.50637496, 0.90657014, 0.80961242, ..., 0.1394964 , 0.79385823,
        0.2762882 ],
       [0.03468621, 0.53313003, 0.99292089, ..., 0.4230128 , 0.2108849 ,
        0.09230487],
       [0.0461575 , 0.16150256, 0.79632612, ..., 0.89293381, 0.93845198,
        0.62955932],
       ...,
       [0.84683034, 0.35304649, 0.56122689, ..., 0.81256859, 0.2897135 ,
        0.11879776],
       [0.85923971, 0.17397005, 0.66882166, ..., 0.57432329, 0.64665505,
        0.21290709],
       [0.00709811, 0.20748841, 0.98216769, ..., 0.65268037, 0.79649382,
        0.46801592]])

In [8]:
b

array([[0.37120554],
       [0.96673875],
       [0.60229222],
       [0.23755133],
       [0.86390498],
       [0.53895326],
       [0.34282706],
       [0.2221143 ],
       [0.16927941],
       [0.68445242],
       [0.2883942 ],
       [0.69580796],
       [0.58972621],
       [0.43623694],
       [0.87810792],
       [0.400288  ],
       [0.56350974],
       [0.28845358],
       [0.773601  ],
       [0.47000491],
       [0.15301559],
       [0.81222359],
       [0.10694048],
       [0.47118869],
       [0.12287603],
       [0.61785496],
       [0.22550935],
       [0.44853928],
       [0.73350798],
       [0.77382521],
       [0.06183592],
       [0.29682167],
       [0.41440976],
       [0.3823239 ],
       [0.6433838 ],
       [0.46910443],
       [0.02546525],
       [0.41417063],
       [0.79543772],
       [0.04333436],
       [0.8369474 ],
       [0.59959243],
       [0.09043194],
       [0.76394477],
       [0.08257427],
       [0.84524131],
       [0.60007322],
       [0.131

In [22]:
%%timeit
x = la.solve(A, b)
x

8.24 ms ± 330 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [21]:
%%timeit
la.inv(A) @ b

27.7 ms ± 557 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
