In [2]:
import numpy as np
from numpy import linalg as la

In [6]:
A = np.array([
    [1, 2],
    [3, 4]
])

trA = np.trace(A)
detA = la.det(A)
I = np.eye(2)

pA = A@A - trA*A + detA*I
pA

array([[-4.4408921e-16,  0.0000000e+00],
       [ 0.0000000e+00, -4.4408921e-16]])

In [7]:
def CH_theorem(A):
    trA = np.trace(A)
    detA = la.det(A)
    I = np.eye(2)

    pA = A@A - trA*A + detA*I
    return pA

A = np.random.randint(0, 10, [2, 2]) # 2x2 matrix with random int between 0 and 10
CH_theorem(A)

array([[0., 0.],
       [0., 0.]])

In [13]:
list(map(CH_theorem, np.random.randint(0, 10, [3, 2, 2])))

[array([[-2.13162821e-14,  0.00000000e+00],
        [ 0.00000000e+00, -2.13162821e-14]]),
 array([[-1.42108547e-14,  0.00000000e+00],
        [ 0.00000000e+00, -1.42108547e-14]]),
 array([[7.10542736e-15, 0.00000000e+00],
        [0.00000000e+00, 7.10542736e-15]])]